.PHONY: clean All

All:
	@echo "----------Building project:[ cartoonify - Debug ]----------"
	@$(MAKE) -f  "cartoonify.mk"
clean:
	@echo "----------Cleaning project:[ cartoonify - Debug ]----------"
	@$(MAKE) -f  "cartoonify.mk" clean
